project:
  type: website
  output-dir: docs
  
website:
  title: "Tayler Kordiak"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: Resume.qmd
      - Projects.qmd
      - icon: github
      aria-label: href: https://github.com/tkordiak15
      target: _blank
      
  page-footer: 
    background: light 
    left: Copyright 2025, Tayler Kordiak
    right: This webiste is built with {{< fa heart title="a heart"}}, [{{< fa brands github title="GitHub octocat logo" >}}](https:github.com/tkordiak15/tkordiak15.github.io){target=blank}, [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html){target=blank} and [Quarto](https://quarto.org/){target=_blank}

format:
  html:
    theme: styles.scss 
    css: styles.css
    toc: true

editor: visual

