project:
  type: website
  output-dir: docs
  
website:
  title: "Tayler Kordiak"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Resume.qmd
      - Projects.qmd
      
format:
  html:
    theme: sandstone
    mainfont: arial
    fontsize: 1.5rem
    fontcolor: "#02060A"
    linkcolor: "#8B29DC"
    monofont: courier new
    css: styles.css
    toc: true
    toc-location: right
  

editor: visual

